#"""Configuration file- Contains all general params and hyperparameters"""

# files- Data related to input files locations
files:
  data_dir: "data"
  ratings_file: "goodreads_rating_p.csv"
  books_authors_file: "goodreads_authors_np.csv"
  books_works_file: "goodreads_works.csv"
  books_genres_file: "goodreads_genres_p.csv"
  books_file: "goodreads_books_eng-final.csv"
  image_source_dir: "data/images-source"
  images_list:  "books_images_names.csv"


# columns_lists- order of columns for various processes during the learning
preprocessed:
  preprocess_col_order: ["book_id", "work_id", 'title', "num_pages", "publication_year","description", "is_ebook", "series", "image_url","read_count", "text_reviews_count", "ratings_count", "average_rating",
  "author_id", "name", "public_year_null", "num_pages_null", "authors_ratings_count", "author_average_rating", "genre"]
  genres_col: [ "poetry", "children", "fantasy, paranormal", "history, historical fiction, biography","comics, graphic", "non-fiction", "mystery, thriller, crime", "young-adult", "romance" ]
  full_genres_col: [ "poetry", "children", "fantasy, paranormal", "history, historical fiction, biography","comics, graphic", "non-fiction", "mystery, thriller, crime", "young-adult", "romance", "fiction"]

num_classes: 10
test_precentage: 0.10
val_precentage: 0.10

hyperparams:
  desc_maxwords: 500
  title_maxwords: 500
  logistic_regre_params:
    C: [0.1, 1.0, 10.0, 100.0]
  random_forest_params:
      n_estimators: [300,500]
      min_samples_leaf: [5,10]
  conv_params:
    transfer_learning:
      top_config: [256,64]
    custom_conv:
      conv_config: [32, 128, 64]
      dense_config: [128, 64]
      kernel: 5
      pool: 2
    batch_size: 64
    epochs: 20
    patience: 3
    image_size: 224
    learning_rate: [0.001, 0.003]

  embedding_params:
    desc_max_voc: 5000
    title_max_voc:  1000
    desc_max_len: 350
    title_max_len: 10
    batch_size: 32
    epochs: 20
    embedding_type: ["spacy", "word2vec"]
    embedding_dim: 300
    patience: 3
    dense_config: [128,64]
    learning_rate: [0.003, 0.001]
    kernel_desc: [5, 10]
    kernel_title: [3,5]
    word2vecwindow_desc: 10
    word2vecwindow_title: 3
    dropout_rates: [0.2, 0.1]
    conv_filters_desc: 64
    conv_filters_title: 16





